### ISSUE TITLE
startSession(args); Error.. 

### ISSUE THREAD

**Issue by vusdo** [alanjames1987/android-hotworddetector#2]
05-26 11:59:28.586 19716-19716/com.alanjames1987.hotworddetector I/HotwordService: onCreate : 
05-26 11:59:28.597 19716-19716/com.alanjames1987.hotworddetector I/HotwordService: onStartCommand
05-26 11:59:28.599 19716-19716/com.alanjames1987.hotworddetector E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: com.alanjames1987.hotworddetector, PID: 19716
                                                                                   java.lang.RuntimeException: Unable to start service com.alanjames1987.hotworddetector.HotwordService@2a2a0026 with Intent { cmp=com.alanjames1987.hotworddetector/.HotwordService }: java.lang.IllegalStateException: Not available until onReady() is called
                                                                                       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2956)
                                                                                       at android.app.ActivityThread.access$2100(ActivityThread.java:151)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5349)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
                                                                                    Caused by: java.lang.IllegalStateException: Not available until onReady() is called
                                                                                       at android.service.voice.VoiceInteractionService.startSession(VoiceInteractionService.java:140)
                                                                                       at com.alanjames1987.hotworddetector.HotwordService.onStartCommand(HotwordService.java:36)
                                                                                       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2939)
                                                                                       at android.app.ActivityThread.access$2100(ActivityThread.java:151) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:135) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5349) 
                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by alanjames1987** [comment]
You should read the description of this repo.

```
Non Functional basic hotword detector using Android API 21 and AlwaysOnHotwordDetector.
```

Additionally being that you have only ever submitted 2 public bug reports I will tell you that a stack trace by itself is often not useful enough. It's often considered to be rude in the same way that it is rude to take food from someone's plate without asking. Many developers prefer to also have a description of the problem, outlining the steps that lead to the crash and subsequent stack trace.

However in this case I have no plans to fix this repo. I uploaded it to share with friends in order to try to fix it. I will add a README.md stating that more clearly so other people visiting the repo won't be confused.
