### ISSUE TITLE
Compile time exception

### ISSUE THREAD

**Issue by ganeshpokale88** [alanjames1987/android-hotworddetector#3]
09-13 20:10:11.942 27517-27517/com.alanjames1987.hotworddetector E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: com.alanjames1987.hotworddetector, PID: 27517
                                                                                   java.lang.NoSuchMethodError: No virtual method startSession(Landroid/os/Bundle;)V in class Lcom/alanjames1987/hotworddetector/HotwordService; or its super classes (declaration of 'com.alanjames1987.hotworddetector.HotwordService' appears in /data/data/com.alanjames1987.hotworddetector/files/instant-run/dex/slice-slice_5-classes.dex)
                                                                                       at com.alanjames1987.hotworddetector.HotwordService.onStartCommand(HotwordService.java:36)
                                                                                       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3028)
                                                                                       at android.app.ActivityThread.-wrap17(ActivityThread.java)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by alanjames1987** [comment]
You should read the description of this repo.

```
Non Functional basic hotword detector using Android API 21 and AlwaysOnHotwordDetector.
```

Additionally being that this is your first public bug report I will tell you that a stack trace by itself is often not useful enough. Many developers prefer to also have a description of the problem, outlining the steps that lead to the crash and subsequent stack trace.

Also, it's common to read other issues submitted in the repo before posting a new one. As I said in issue #2 

> I have no plans to fix this repo. I uploaded it to share with friends in order to try to fix it. I will add a README.md stating that more clearly so other people visiting the repo won't be confused.
